routes/web.php
<?php

use App\Http\Middleware\RedirectIfAuthenticated;

Route::get('/', function () { 	return view('welcome');  });

Auth::routes();

//+++++++++++++++++++=Route::get('/home', 'HomeController@index')->name('home');

Route::get('contact', 'ContactController@index')->name('contact');


Route::redirect('/admin', '/admin/dashboard', 301);
Route::redirect('/auteur', '/auteur/dashboard', 301);

///ADMIN
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Categories
        Route::get('create_categorie', 'CategorieController@showFormCreate')->name('showFormCreate');
        Route::post('create_categorie', 'CategorieController@create')->name('CreateCategorie');
        Route::get('liste_categories', 'CategorieController@show')->name('liste_categories');
        Route::get('edit_categorie/{id}', 'CategorieController@edit')->name('edit_categorie');
        Route::post('update_categorie', 'CategorieController@update')->name('update_categorie');
        Route::get('delete_categorie/{id}', 'CategorieController@delete')->name('delete_categorie');

        // Roles
        Route::get('liste_roles', 'RoleController@show')->name('liste_roles');
        Route::get('create_role_view', 'RoleController@create_role_view')->name('create_role_view');
        Route::post('create_role', 'RoleController@store')->name('create_role');
        Route::get('edit_role/{id}', 'RoleController@edit')->name('edit_role');
        Route::post('update_role', 'RoleController@update')->name('update_role');
        Route::get('delete_role/{id}', 'RoleController@delete')->name('delete_role');

});

//AUTEUR
Route::group(['as' => 'auteur.', 'prefix' => 'auteur', 'namespace' => 'Auteur', 'middleware' => ['auth', 'auteur']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    //Posts
    Route::get('posts','PostController@show')->name('posts');
    Route::get('create_post','PostController@create_post')->name('create_post');
    Route::post('create_post','PostController@store')->name('create_post');
});

resources/views/backend/admin/categories/categories.blade.php
@extends('backend.layout')

@section('titre_page') Liste Categorie
<a href="{{ route('admin.CreateCategorie')}}" class="btn btn-lg btn-primary">
    <i class="fa fa-plus" aria-hidden="true"></i>
    </a>
@endsection

@push('css')
  <link href="{{ asset('backend/js/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush


@section('content')

        <div class="card shadow col-md-12">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Catégories</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Nom</th>
                      <th>Description</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                        <th>Nom</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                  </tfoot>
                  <tbody>
                        @foreach ($categories as $c)
                            <tr>
                                <td>{{  $c->name }}</td>
                                <td>{{ str_limit($c->description, $limit = 50, $end = ' ... etc ...') }}</td>
                                <td>
                                    <a href="{{ route('admin.edit_categorie', $c->id) }}"><i class="fas fa-lg fa-edit"></i></a> |
                                    <a class="" onclick="return confirm('Êtes vous sûr de votree action ?')" href="{{  route('admin.delete_categorie', $c->id) }}">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>

@endsection


@push('js')
  <script src="{{ asset('backend/js/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('backend/js/datatables/dataTables.bootstrap4.min.js') }}"></script>
  <script>
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
  </script>
@endpush

resources/views/backend/admin/categories/create_ategorie.blade.php
@extends('backend.layout')

@section('titre_page') Nouvelle Categorie @endsection

@section('content')


        <form action="{{ route('admin.CreateCategorie') }}" method="post">
            @csrf

            <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Catégorie</label>
                    <div class="col-md-8">
                        <input id="name" type="text" class="form-control  @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" autofocus>
                        @error('name')
                            <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                        @enderror
                    </div>
            </div>

            <div class="form-group row">
                <label for="description" class="col-md-4 col-form-label text-md-right">Catégorie</label>
                <div class="col-md-8">
                    <textarea name="description" id="description" cols="30" rows="10" class="form-control  @error('description') is-invalid @enderror" name="description" autofocus>{{ old('description') }}</textarea>

                    @error('description')
                        <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                    @enderror
                </div>
             </div>

             <button type="submit" class="btn btn-primary btn-lg col-md-12">Submit</button>

        </form>

@endsection

resources/views/backend/admin/categories/edit_categorie.blade.php
@extends('backend.layout')

@section('titre_page') Modifier Catégorie @endsection

@section('content')


        <form action="{{ route('admin.update_categorie') }}" method="post">
            @csrf

            <input type="hidden" name="categorie_id" value="{{ $categorie->id }}">

            <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Catégorie</label>
                    <div class="col-md-8">
                        <input id="name" type="text" class="form-control  @error('name') is-invalid @enderror" name="name" value="{{ $categorie->name }}" autofocus>
                        @error('name')
                            <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                        @enderror
                    </div>
            </div>

            <div class="form-group row">
                <label for="description" class="col-md-4 col-form-label text-md-right">Catégorie</label>
                <div class="col-md-8">
                    <textarea name="description" id="description" cols="30" rows="10" class="form-control  @error('description') is-invalid @enderror" name="description"  autofocus>{{ $categorie->description }}</textarea>
                    @error('description')
                        <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                    @enderror
                </div>
             </div>

             <button type="submit" class="btn btn-success btn-lg col-md-12">Enregister</button>

        </form>

@endsection