routes/web.php
<?php

use App\Http\Middleware\RedirectIfAuthenticated;

Route::get('/', function () { 	return view('welcome');  });

Auth::routes();

//+++++++++++++++++++=Route::get('/home', 'HomeController@index')->name('home');

Route::get('contact', 'ContactController@index')->name('contact');


Route::redirect('/admin', '/admin/dashboard', 301);
Route::redirect('/auteur', '/auteur/dashboard', 301);

///ADMIN
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Categories
        Route::get('create_categorie', 'CategorieController@showFormCreate')->name('showFormCreate');
        Route::post('create_categorie', 'CategorieController@create')->name('CreateCategorie');
        Route::get('liste_categories', 'CategorieController@show')->name('liste_categories');
        Route::get('edit_categorie/{id}', 'CategorieController@edit')->name('edit_categorie');
        Route::post('update_categorie', 'CategorieController@update')->name('update_categorie');
        Route::get('delete_categorie/{id}', 'CategorieController@delete')->name('delete_categorie');

        // Roles
        Route::get('liste_roles', 'RoleController@show')->name('liste_roles');
        Route::get('create_role_view', 'RoleController@create_role_view')->name('create_role_view');
        Route::post('create_role', 'RoleController@store')->name('create_role');
        Route::get('edit_role/{id}', 'RoleController@edit')->name('edit_role');
        Route::post('update_role', 'RoleController@update')->name('update_role');
        Route::get('delete_role/{id}', 'RoleController@delete')->name('delete_role');

});

//AUTEUR
Route::group(['as' => 'auteur.', 'prefix' => 'auteur', 'namespace' => 'Auteur', 'middleware' => ['auth', 'auteur']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    //Posts
    Route::get('posts','PostController@show')->name('posts');
    Route::get('create_post','PostController@create_post')->name('create_post');
    Route::post('create_post','PostController@store')->name('create_post');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = [
        'name',
        'slug'
    ];

    public function users(){
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/API/RoleController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\RoleRequest;
use App\Role;

class RoleController extends Controller {

    public function show(){
        $roles = Role::all();
        return view('backend.admin.roles.roles')->with(compact('roles'));
    }

    public function create_role_view(){
        return view('backend.admin.roles.create_role');
    }

    public function store(RoleRequest $request){
        try{
            Role::create([
                'name' => $request->name,
                'slug' => $request->slug
            ]);
            $request->session()->flash('success', 'Opération effectuée avec succès !');
            return view('backend.admin.roles.roles')->with('roles',Role::all());
         }
         catch(\Exception $e){
            $request->session()->flash('danger', 'Error :  '. $e->getMessage());
            return view('backend.admin.roles.roles')->with('roles',Role::all());
         }
    }

    public function edit($id){
        return view('backend.admin.roles.edit_role')->with('role',Role::find($id));
    }

    public function update(RoleRequest $request){
        try{
            $r = Role::find($request->role_id);
                $r->name = $request->name;
                $r->slug = $request->slug;
            $r->save();
            $request->session()->flash('success', 'Opération effectuée avec succès !');
            return view('backend.admin.roles.roles')->with('roles',Role::all());
         }
         catch(\Exception $e){
            $request->session()->flash('danger', 'Error :  '. $e->getMessage());
            return view('backend.admin.roles.roles')->with('roles',Role::all());
         }
    }

    public function delete(Request $request,$id){
        try{
            $r = Role::find($id);
            $r->delete();
            $request->session()->flash('warning', 'Vous venez de supprimez un role!');
            return redirect()->back();
         }
         catch(\Exception $e){
            $request->session()->flash('danger', 'Error :  '. $e->getMessage());
            return redirect()->back();
         }
    }
}

resources/views/backend/admin/roles/create_role.blade.php
@extends('backend.layout')

@section('titre_page') Ajout Role @endsection

@section('content')


        <form action="{{ route('admin.create_role') }}" method="post">
            @csrf

            <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Role</label>
                    <div class="col-md-8">
                        <input id="name" type="text" class="form-control  @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" autofocus>
                        @error('name')
                            <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                        @enderror
                    </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">Abreviation</label>
                <div class="col-md-8">
                    <input id="slug" type="text" class="form-control  @error('slug') is-invalid @enderror" name="slug" value="{{ old('slug') }}" autofocus>
                    @error('slug')
                        <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                    @enderror
                </div>
        </div>

             <button type="submit" class="btn btn-primary btn-lg col-md-12">Submit</button>

        </form>

@endsection

resources/views/backend/admin/roles/edit_role.blade.php
@extends('backend.layout')

@section('titre_page')Edit Role @endsection

@section('content')


        <form action="{{ route('admin.update_role') }}" method="post">
            @csrf

            <input type="hidden" name="role_id" value="{{ $role->id }}">

            <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Role</label>
                    <div class="col-md-8">
                        <input id="name" type="text" class="form-control  @error('name') is-invalid @enderror" name="name" value="{{ $role->name }}" autofocus>
                        @error('name')
                            <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                        @enderror
                    </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">Abreviation</label>
                <div class="col-md-8">
                    <input id="slug" type="text" class="form-control  @error('slug') is-invalid @enderror" name="slug" value="{{ $role->name }}" autofocus>
                    @error('slug')
                        <span class="invalid-feedback" role="alert">  <strong>{{ $message }}</strong> </span>
                    @enderror
                </div>
        </div>

             <button type="submit" class="btn btn-success btn-lg col-md-12">Modifier </button>

        </form>

@endsection

resources/views/backend/admin/roles/roles.blade.php
@extends('backend.layout')



@section('content')

        <div class="card shadow col-md-12">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Roles</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Role</th>
                      <th>Slug</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Role</th>
                        <th>Slug</th>
                        <th>Actions</th>
                    </tr>
                  </tfoot>
                  <tbody>
                        @foreach ($roles as $r)
                            <tr>
                                <td>{{  $r->id }}</td>
                                <td>{{  $r->name }}</td>
                                <td>{{  $r->slug }}</td>
                                <td>
                                    <a href="{{ route('admin.edit_role', $r->id) }}"><i class="fas fa-lg fa-edit"></i></a> |
                                    <a class="" onclick="return confirm('Êtes vous sûr de votree action ?')" href="{{  route('admin.delete_role', $r->id) }}">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>

@endsection


@push('js')
  <script src="{{ asset('backend/js/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('backend/js/datatables/dataTables.bootstrap4.min.js') }}"></script>
  <script>
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
  </script>
@endpush