routes/web.php
<?php

use App\Http\Middleware\RedirectIfAuthenticated;

Route::get('/', function () { 	return view('welcome');  });

Auth::routes();

//+++++++++++++++++++=Route::get('/home', 'HomeController@index')->name('home');

Route::get('contact', 'ContactController@index')->name('contact');


Route::redirect('/admin', '/admin/dashboard', 301);
Route::redirect('/auteur', '/auteur/dashboard', 301);

///ADMIN
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Categories
        Route::get('create_categorie', 'CategorieController@showFormCreate')->name('showFormCreate');
        Route::post('create_categorie', 'CategorieController@create')->name('CreateCategorie');
        Route::get('liste_categories', 'CategorieController@show')->name('liste_categories');
        Route::get('edit_categorie/{id}', 'CategorieController@edit')->name('edit_categorie');
        Route::post('update_categorie', 'CategorieController@update')->name('update_categorie');
        Route::get('delete_categorie/{id}', 'CategorieController@delete')->name('delete_categorie');

        // Roles
        Route::get('liste_roles', 'RoleController@show')->name('liste_roles');
        Route::get('create_role_view', 'RoleController@create_role_view')->name('create_role_view');
        Route::post('create_role', 'RoleController@store')->name('create_role');
        Route::get('edit_role/{id}', 'RoleController@edit')->name('edit_role');
        Route::post('update_role', 'RoleController@update')->name('update_role');
        Route::get('delete_role/{id}', 'RoleController@delete')->name('delete_role');

});

//AUTEUR
Route::group(['as' => 'auteur.', 'prefix' => 'auteur', 'namespace' => 'Auteur', 'middleware' => ['auth', 'auteur']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    //Posts
    Route::get('posts','PostController@show')->name('posts');
    Route::get('create_post','PostController@create_post')->name('create_post');
    Route::post('create_post','PostController@store')->name('create_post');
});

resources/views/backend/admin/dashboard.blade.php
@extends('backend.layout')

@section('content')


        <!-- All User Info -->
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Utilisateurs</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800">{{ \App\User::count()  }}</div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-users fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- All Role Info -->
        <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Roles</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ \App\Role::count()  }}</div>
                        </div>
                        <div class="col-auto">
                          <i class="fas fa-shield-alt fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    </div>
                </div>
        </div>

        <!-- All Post Info -->
        <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Articles</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ \App\Post::count()  }}</div>
                        </div>
                        <div class="col-auto">
                        <i class="fas fa-sticky-note fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    </div>
               </div>
        </div>

        <!-- All Role Info -->
        <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"> <a href="{{ route('admin.liste_categories') }}">Catégories</a> </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ \App\Categorie::count()  }}</div>
                        </div>
                        <div class="col-auto">
                        <i class="fas fa-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    </div>
                </div>
        </div>

@endsection

resources/views/backend/admin/menu_admin.blade.php
      <!-- Heading -->
      <div class="sidebar-heading">
            Gestions des utilisateurs
          </div>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-fw fa-users"></i>
              <span>Utilisateurs</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('admin.liste_roles')  }}">
            <i class="fas fa-shield-alt"></i>
            <span>Roles</span></a>
          </li>
          <!-- Divider -->
          <hr class="sidebar-divider">
          <!-- Heading -->
          <div class="sidebar-heading">
            Gestion des Articles
          </div>
         <li class="nav-item">
            <a class="nav-link" href="{{ route('admin.liste_categories')}}">
              <i class="fas fa-fw fa-list"></i>
              <span>Categories</span></a>
         </li>
         <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-fw fa-chart-area"></i>
              <span>Articles</span></a>
          </li>