routes/web.php
<?php

use App\Http\Middleware\RedirectIfAuthenticated;

Route::get('/', function () { 	return view('welcome');  });

Auth::routes();

//+++++++++++++++++++=Route::get('/home', 'HomeController@index')->name('home');

Route::get('contact', 'ContactController@index')->name('contact');


Route::redirect('/admin', '/admin/dashboard', 301);
Route::redirect('/auteur', '/auteur/dashboard', 301);

///ADMIN
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

        // Categories
        Route::get('create_categorie', 'CategorieController@showFormCreate')->name('showFormCreate');
        Route::post('create_categorie', 'CategorieController@create')->name('CreateCategorie');
        Route::get('liste_categories', 'CategorieController@show')->name('liste_categories');
        Route::get('edit_categorie/{id}', 'CategorieController@edit')->name('edit_categorie');
        Route::post('update_categorie', 'CategorieController@update')->name('update_categorie');
        Route::get('delete_categorie/{id}', 'CategorieController@delete')->name('delete_categorie');

        // Roles
        Route::get('liste_roles', 'RoleController@show')->name('liste_roles');
        Route::get('create_role_view', 'RoleController@create_role_view')->name('create_role_view');
        Route::post('create_role', 'RoleController@store')->name('create_role');
        Route::get('edit_role/{id}', 'RoleController@edit')->name('edit_role');
        Route::post('update_role', 'RoleController@update')->name('update_role');
        Route::get('delete_role/{id}', 'RoleController@delete')->name('delete_role');

});

//AUTEUR
Route::group(['as' => 'auteur.', 'prefix' => 'auteur', 'namespace' => 'Auteur', 'middleware' => ['auth', 'auteur']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    //Posts
    Route::get('posts','PostController@show')->name('posts');
    Route::get('create_post','PostController@create_post')->name('create_post');
    Route::post('create_post','PostController@store')->name('create_post');
});

resources/views/frontend/partials/css.blade.php
  <link href="{{ asset('frontend/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('frontend/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href="{{ asset('frontend/css/clean-blog.min.css') }}" rel="stylesheet">

resources/views/frontend/partials/footer.blade.php
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">

                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

resources/views/frontend/partials/header.blade.php
  <header class="masthead" style="background-image: url({{ asset('frontend/img/home-bg.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1> {{ env('APP_NAME') }} </h1>
            <span class="subheading">{{ env('APP_TITRE_DESCRIPTION')  }}
</span>
          </div>
        </div>
      </div>
    </div>
  </header>

resources/views/frontend/partials/js.blade.php
<script src="{{ asset('frontend/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('frontend/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('frontend/js/clean-blog.min.js') }}"></script>

resources/views/frontend/partials/menu.blade.php
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">{{ env('APP_NAME') }}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Accueil</a>
          </li>
          <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
                <div class="dropdown-menu">
                    @foreach (\App\Categorie::all() as $c )
                        <a class="dropdown-item" href="#">{{  $c->name }}</a>
                        <div class="dropdown-divider"></div>
                    @endforeach
                </div>
            </li>
          @guest
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">Se connecter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">S'inscrire</a>
            </li>
          @else
            {{-- @if(Auth::user()->role->id == 1) --}}
                @admin
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}">Dashbord</a>
                </li>
                @endadmin
                @auteur
            {{-- @elseif(Auth::user()->role->id == 2) --}}
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('auteur.dashboard') }}">Dashbord</a>
                </li>
                @endauteur
            {{-- @endif --}}
          @endguest

          <li class="nav-item">
            <a class="nav-link" href="{{ route('contact') }}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>